"""tenant api keys and tenant admin columns

Issue #31. Three things happen here, and they belong in one revision because a database
that had any two of them without the third would be inconsistent.

**A tenant gets a first-class ``slug``.** Until now the external identity of a tenant — the
value a customer's form sends in ``X-LeadQuali-Tenant``, and the thing every ``tenant_id``
in the ports is — was recoverable only from ``icp_config->>'tenant_id'``. That made it a
property of a free-form ``jsonb`` document: nothing stopped two rows claiming the same slug,
and a config rewrite could change a tenant's identity without changing its primary key. The
column is backfilled from exactly that expression, so no existing row moves, and it is then
``NOT NULL``, ``UNIQUE`` and shape-checked. The invariant that ``id =
uuid5(TENANT_ID_NAMESPACE, slug)`` is enforced by ``leadquali.app.tenants.TenantService`` on
create, because Postgres cannot compute a uuid5 inside a CHECK.

**Keys move to their own table and ``tenants.api_key_hash`` is dropped.** One key per tenant
cannot be rotated without downtime, which is what the issue asks for. ``tenant_api_keys``
holds many rows per tenant, each with its own ``expires_at`` (the rotation overlap) and
``revoked_at`` (immediate). The old column is *dropped* rather than left in place: a second
location a live key can live in is how one gets missed during a revocation, and "we revoked
it but it still worked" is the worst possible bug in this part of the system. The downgrade
restores the column, empty — the hashes it used to hold were SHA-256 of a whole key under
the pre-#31 scheme and are not convertible to the new format, so there is nothing to put
back and pretending otherwise would be worse than an honest NULL.

**Per-tenant rate limits land on the row.** ``rate_limit_per_minute`` and
``rate_limit_burst``, enforced in the application by
``leadquali.api.ratelimit.TenantRateLimiter``. See ``docs/tenant-onboarding.md`` for why
this is not an API Gateway usage plan.

Written by hand rather than autogenerated, because autogenerate cannot know that ``slug``
is backfilled from ``icp_config`` rather than defaulted, and would emit an ``ADD COLUMN
... NOT NULL`` that fails on any non-empty table. ``tests/integration/test_migrations.py``
still asserts that re-running autogenerate after ``upgrade head`` produces an empty diff.

Revision ID: 7c1f2ad50b93
Revises: 484c0bafc202
Create Date: 2026-09-04 09:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7c1f2ad50b93"
down_revision: str | None = "484c0bafc202"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mirrors ``leadquali.adapters.db_schema.TENANT_SLUG_SQL_PATTERN``. Restated as a literal
#: because a migration has to keep working when the application moves on.
SLUG_PATTERN = "^[a-z0-9][a-z0-9_-]{0,62}$"


def upgrade() -> None:
    """Apply this revision."""
    # --- tenants ---------------------------------------------------------------------
    #
    # Added nullable, backfilled, then constrained. The three-step dance is what makes this
    # safe against a table that already has rows: an ADD COLUMN NOT NULL with no default
    # fails outright, and a default would silently give every existing tenant the same slug.
    op.add_column("tenants", sa.Column("slug", sa.Text(), nullable=True))
    op.execute(
        "UPDATE tenants SET slug = icp_config->>'tenant_id' "
        "WHERE slug IS NULL AND icp_config->>'tenant_id' IS NOT NULL"
    )
    # A row whose config carries no tenant_id at all cannot be given a meaningful slug, and
    # guessing one would silently break every signed request that tenant makes. Fail the
    # migration instead, naming the rows: this is a two-row table in every environment that
    # exists, and an operator can fix it in a minute.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM tenants WHERE slug IS NULL) THEN
                RAISE EXCEPTION
                    'cannot derive tenants.slug: some rows have no tenant_id in icp_config. '
                    'Set it (or tenants.slug) by hand and re-run this migration.';
            END IF;
        END $$;
        """
    )
    op.alter_column("tenants", "slug", existing_type=sa.Text(), nullable=False)
    op.create_unique_constraint(op.f("uq_tenants_slug"), "tenants", ["slug"])
    op.create_check_constraint(
        op.f("ck_tenants_slug_is_a_slug"), "tenants", f"slug ~ '{SLUG_PATTERN}'"
    )

    op.add_column(
        "tenants",
        sa.Column(
            "rate_limit_per_minute", sa.Integer(), server_default=sa.text("60"), nullable=False
        ),
    )
    op.add_column(
        "tenants",
        sa.Column("rate_limit_burst", sa.Integer(), server_default=sa.text("10"), nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_tenants_rate_limits_are_positive"),
        "tenants",
        "rate_limit_per_minute > 0 AND rate_limit_burst > 0",
    )
    op.add_column(
        "tenants",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("tenants", "api_key_hash")

    # --- tenant_api_keys -------------------------------------------------------------
    op.create_table(
        "tenant_api_keys",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key_id", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "key_id <> '' AND key_hash <> ''",
            name=op.f("ck_tenant_api_keys_key_material_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_api_keys_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_api_keys")),
        sa.UniqueConstraint("key_id", name=op.f("uq_tenant_api_keys_key_id")),
    )
    op.create_index(
        "ix_tenant_api_keys_tenant_id_created_at",
        "tenant_api_keys",
        ["tenant_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    """Revert this revision.

    ``tenants.api_key_hash`` comes back NULL for every row. The keys themselves were never
    stored — that is the point of the table being dropped here — so a downgrade genuinely
    loses every credential, and any deployment that runs it has to re-issue keys. Said
    plainly here because the alternative is an operator discovering it from 401s.
    """
    op.drop_index("ix_tenant_api_keys_tenant_id_created_at", table_name="tenant_api_keys")
    op.drop_table("tenant_api_keys")

    op.add_column("tenants", sa.Column("api_key_hash", sa.Text(), nullable=True))
    op.drop_column("tenants", "updated_at")
    op.drop_constraint(op.f("ck_tenants_rate_limits_are_positive"), "tenants", type_="check")
    op.drop_column("tenants", "rate_limit_burst")
    op.drop_column("tenants", "rate_limit_per_minute")
    op.drop_constraint(op.f("ck_tenants_slug_is_a_slug"), "tenants", type_="check")
    op.drop_constraint(op.f("uq_tenants_slug"), "tenants", type_="unique")
    op.drop_column("tenants", "slug")
