"""tenant config versions and golden-set promotions

Issue #36. Two tables, in one revision because the admin ships as one surface and a
database with the editor's audit table but not the review screen's idempotency key would
be half a deployment.

**``tenant_config_versions``** is the rubric's edit history. Invariant 1 makes the rubric
configuration rather than code, which is what lets a customer be onboarded without a
deploy — and which also means the highest-risk action in the product has no build, no code
review and no ``git revert`` behind it. This table is all three. ``config`` holds the
**whole** document as it stood after each change rather than a patch: a chain of patches is
one bad apply away from being unreplayable, and the point of the table is that a bad rubric
can be undone at 3am by somebody who is not the person who wrote it. ``UNIQUE (tenant_id,
version)`` is the mechanism and not belt and braces — the version is allocated from this
table inside the writing transaction, so the constraint is what settles two operators
saving at once. ``ON DELETE CASCADE`` to ``tenants``, like ``tenant_api_keys``: it is a
record *about* the customer's configuration and meaningless without them.

**Version 1 is seeded for every existing tenant**, from that tenant's current
``icp_config``, with ``changed_by = 'migration'``. Without it the first edit has nothing to
diff against, and the editor's whole safety story is the diff. This is a backfill inside a
migration, which the #33 revision deliberately avoided — the difference is the size: one
row per tenant, read from a table with a handful of rows in it, rather than an aggregate
over every assessment in the schema.

**``golden_promotions``** records the decision to promote a lead into the eval golden set
(#22) and the human label that goes with it. It holds no copy of the payload: the golden
set is a git-committed JSONL file appended to by a human, so the admin renders the line
from the lead on demand, and a pseudonymised copy stored here would be a second home for
data derived from ``leads.raw_payload`` — outside the one place invariant 5 allows personal
data to live, and outside what #37's retention job purges. ``UNIQUE (tenant_id, lead_id)``
is what makes promotion idempotent: the eval harness would weigh a doubly-promoted lead
twice.

Written by hand rather than autogenerated so the reasoning above sits with the DDL;
``tests/integration/test_migrations.py`` still asserts that autogenerate produces an empty
diff after ``upgrade head``.

Revision ID: b6d2e94f7a13
Revises: a3f5c2b81d47
Create Date: 2026-09-16 09:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6d2e94f7a13"
# Chained onto #33's usage rollup. #35 is being written against the same parent, so
# whichever of the two lands second re-points this one line and nothing else.
down_revision: str | None = "a3f5c2b81d47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: ``changed_by`` on the seeded rows. Mirrors
#: ``leadquali.app.config_versions.MIGRATION_SUBJECT``, restated as a literal because a
#: migration has to keep working when the application moves on. A visible non-person is
#: the honest answer to "who made this change?" for a row nobody made.
MIGRATION_SUBJECT = "migration"

#: The note on the seeded rows, so the history screen says where version 1 came from.
SEED_NOTE = "seeded from the tenant's stored config when the edit history was added"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "tenant_config_versions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_by", sa.Text(), nullable=False),
        sa.Column(
            "changed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "changed_by <> ''", name=op.f("ck_tenant_config_versions_changed_by_not_blank")
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_tenant_config_versions_version_is_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_config_versions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_config_versions")),
        sa.UniqueConstraint(
            "tenant_id", "version", name=op.f("uq_tenant_config_versions_tenant_id_version")
        ),
    )

    # The seed. One row per tenant, from the config that tenant is running right now, so
    # that the first edit through the admin has something to diff against. `changed_at`
    # borrows the tenant's own `updated_at`: it is the closest thing on file to when this
    # config actually became current, and inventing `now()` would claim every rubric in
    # the fleet changed at deploy time.
    op.execute(
        sa.text(
            "INSERT INTO tenant_config_versions "
            "(tenant_id, version, config, changed_by, changed_at, note) "
            "SELECT id, 1, icp_config, :changed_by, updated_at, :note FROM tenants"
        ).bindparams(changed_by=MIGRATION_SUBJECT, note=SEED_NOTE)
    )

    op.create_table(
        "golden_promotions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column("expected_tier", sa.String(length=16), nullable=False),
        sa.Column("promoted_by", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "promoted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "case_id <> '' AND promoted_by <> ''",
            name=op.f("ck_golden_promotions_promotion_fields_not_blank"),
        ),
        sa.CheckConstraint(
            "expected_tier IN ('hot', 'warm', 'cold', 'disqualified')",
            name=op.f("ck_golden_promotions_expected_tier_known"),
        ),
        sa.CheckConstraint(
            "length(note) >= 20", name=op.f("ck_golden_promotions_note_is_a_rationale")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name=op.f("fk_golden_promotions_tenant_id_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_golden_promotions")),
        sa.UniqueConstraint("case_id", name=op.f("uq_golden_promotions_case_id")),
        sa.UniqueConstraint(
            "tenant_id", "lead_id", name=op.f("uq_golden_promotions_tenant_id_lead_id")
        ),
    )
    op.create_index(
        op.f("ix_golden_promotions_tenant_id_promoted_at"),
        "golden_promotions",
        ["tenant_id", "promoted_at"],
        unique=False,
    )


def downgrade() -> None:
    """Revert this revision.

    Both tables are dropped, and ``tenant_config_versions`` is the one that hurts: it is
    the *only* record of who changed a rubric and to what, and unlike #33's rollup nothing
    can recompute it. Downgrading past this revision therefore means exporting the table
    first if the history is worth anything, which it is — that is the whole reason it
    exists. ``golden_promotions`` loses only the idempotency record; the golden set itself
    is in git.
    """
    op.drop_index(
        op.f("ix_golden_promotions_tenant_id_promoted_at"), table_name="golden_promotions"
    )
    op.drop_table("golden_promotions")
    op.drop_table("tenant_config_versions")
