"""usage rollup and tenant quota

Issue #33. Two things, in one revision because the soft quota is measured in the units the
rollup defines and a database with one of them but not the other could not answer "is this
tenant over their plan?".

**``usage_daily``** is a derived table: one row per tenant per UTC calendar day, every
column recomputable from ``leads`` and ``assessments``. It exists so that a billing read
for a month is a range scan over thirty small rows rather than an aggregate over every
assessment a tenant has ever had — a query whose cost grows forever while its answer stays
the same size. The primary key is the natural key ``(tenant_id, usage_date)``: a second row
for one tenant-day is not a new fact, it is a bug, and it is also the conflict target the
idempotent ``INSERT ... ON CONFLICT DO UPDATE`` rollup needs. Token counters are ``bigint``
rather than the ``integer`` used on ``assessments``: no single call approaches 2^31, and a
busy tenant passes two billion input tokens inside a year.

The foreign key cascades, unlike ``leads``, which restricts. Nothing here is a record of
anything — it is a cache of a ``SUM`` — so losing it with the tenant destroys nothing that
cannot be recomputed, and blocking a deletion on a derived table would be theatre.

**``tenants.monthly_lead_quota`` and ``tenants.quota_alert_fraction``** are the soft quota.
The quota is nullable and defaults to NULL (unlimited) because a quota that appeared by
accident would start warning somebody about a customer who never agreed to one. The alert
fraction is NOT NULL with a 0.80 default and a CHECK that keeps it inside (0, 1] — an alert
at 0% fires on the first lead of every month and one above 100% can never fire at all, and
a setting that silently does nothing is worse than one the database refuses.

**No backfill.** ``usage_daily`` is created empty rather than populated from the history in
``assessments``: the rollup is idempotent by construction, so ``usagectl rollup <tenant>
--from ... --to ...`` reproduces any range of history on demand, and a backfill inside a
migration would hold a transaction open over a full table scan of the largest table in the
schema during a deploy. ``docs/metering-and-billing.md`` documents the command.

Written by hand rather than autogenerated so the reasoning above sits with the DDL;
``tests/integration/test_migrations.py`` still asserts that autogenerate produces an empty
diff after ``upgrade head``.

Revision ID: a3f5c2b81d47
Revises: 7c1f2ad50b93
Create Date: 2026-09-05 10:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a3f5c2b81d47"
down_revision: str | None = "7c1f2ad50b93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mirrors ``leadquali.adapters.db_schema.DEFAULT_QUOTA_ALERT_FRACTION``. Restated as a
#: literal because a migration has to keep working when the application moves on.
DEFAULT_QUOTA_ALERT_FRACTION = "0.80"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "usage_daily",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("leads_ingested", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("leads_assessed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("leads_billable", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("assessments_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cache_read_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cache_creation_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=14, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "leads_ingested >= 0 AND leads_assessed >= 0 AND leads_billable >= 0"
            " AND assessments_failed >= 0 AND input_tokens >= 0 AND output_tokens >= 0"
            " AND cache_read_tokens >= 0 AND cache_creation_tokens >= 0 AND cost_usd >= 0",
            name=op.f("ck_usage_daily_usage_is_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_usage_daily_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "usage_date", name=op.f("pk_usage_daily")),
    )

    # The soft quota. Both columns are additive and neither changes any existing row's
    # behaviour: every tenant on file comes out of this migration unlimited, which is what
    # they are today.
    op.add_column("tenants", sa.Column("monthly_lead_quota", sa.Integer(), nullable=True))
    op.add_column(
        "tenants",
        sa.Column(
            "quota_alert_fraction",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text(DEFAULT_QUOTA_ALERT_FRACTION),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_tenants_monthly_lead_quota_is_positive"),
        "tenants",
        "monthly_lead_quota IS NULL OR monthly_lead_quota > 0",
    )
    op.create_check_constraint(
        op.f("ck_tenants_quota_alert_fraction_is_a_fraction"),
        "tenants",
        "quota_alert_fraction > 0 AND quota_alert_fraction <= 1",
    )


def downgrade() -> None:
    """Revert this revision.

    ``usage_daily`` is dropped outright and nothing is lost that matters: every row in it
    is recomputable from ``leads`` and ``assessments`` by re-running the rollup. The two
    tenant columns go with it, which does lose the configured quotas — they are policy, not
    derived data — so a downgrade means writing the customers' plan sizes down first.
    """
    op.drop_constraint(
        op.f("ck_tenants_quota_alert_fraction_is_a_fraction"), "tenants", type_="check"
    )
    op.drop_constraint(op.f("ck_tenants_monthly_lead_quota_is_positive"), "tenants", type_="check")
    op.drop_column("tenants", "quota_alert_fraction")
    op.drop_column("tenants", "monthly_lead_quota")
    op.drop_table("usage_daily")
