"""stripe billing: events, usage reports and the tenant link

Issue #35. Two tables and three columns, in one revision because a database with the
tenant link but not the event table (or the other way round) could not answer either of
the two questions billing asks: "who is this Stripe customer?" and "have we already
reported this day?".

**``stripe_events``** is the webhook inbox. Its primary key is Stripe's own ``evt_...``,
and that is the whole idempotency story: Stripe retries a delivery it did not see a 200
for, the retry carries the same id, and the route's ``INSERT ... ON CONFLICT (event_id) DO
NOTHING`` therefore makes a retry a no-op — including while the first copy is still
``pending``, which is exactly when a retry is most likely, because a pending row means we
were slow. ``payload`` is stored verbatim as ``jsonb``: it is the evidence of what Stripe
actually said, and the fields this build does not model today are the ones an incident
will want tomorrow.

``stripe_events.tenant_id`` is **nullable, and it is the one deliberate exception to
invariant 4** ("tenant_id on every table and every repository method"). A webhook arrives
before we know whose it is: the event names a Stripe *customer*, and resolving that to a
tenant is a read the verifying route does not do. Refusing to store an event we could not
attribute would mean discarding the only record that it arrived. The column is filled in by
the handler once the customer resolves; it is ``ON DELETE SET NULL`` so that removing a
tenant does not destroy billing history; and every *read* that is about a tenant filters on
it. The exception is written here, in ``StripeEventRow``'s docstring and in
``leadquali.app.billing``, because an unexplained exception to an invariant is how the
invariant dies.

The pending index is **partial**. The drain's only query is "pending, oldest first", and an
index over every webhook we have ever received would grow forever while the part of it
anybody reads stays the size of the backlog.

**``usage_reports``** exists because double-reporting overbills a customer and the issue is
explicit that this is worse than under-reporting. The primary key is the natural key
``(tenant_id, usage_date)``, so a day already reported cannot be reported again however
many times the scheduled job runs or however it is retried. ``external_id`` is the
deterministic handle sent to Stripe (a UUID5 of tenant and day) and carries its own unique
constraint — a cheap second guard that would catch a bug in the *derivation*, where the
primary key only catches one at the call site.

Its foreign key **restricts**, unlike ``usage_daily`` next to it, which cascades. That
table is a cache of a ``SUM`` and losing it destroys nothing; this one records something we
told a payment processor about a customer's money, and a tenant deleted out from under it
would let a re-created tenant report the same days again. #37's purge must delete these
deliberately, which is the point.

**``tenants.stripe_customer_id`` and ``stripe_subscription_id`` are UNIQUE.** Two tenants
sharing a Stripe customer would cross-bill one of them for the other's leads, and the
database is the only place that can make that impossible rather than merely unlikely. Both
are nullable and Postgres treats NULLs as distinct, so any number of tenants may have no
customer. **``dunning_until``** is when a failed payment's grace period runs out; the
tenant stays ``active`` for the whole window, and a scheduled sweep suspends it afterwards.

No backfill. Every existing tenant comes out of this migration unlinked and undunned, which
is what they are today.

Written by hand rather than autogenerated so the reasoning above sits with the DDL;
``tests/integration/test_migrations.py`` still asserts that autogenerate produces an empty
diff after ``upgrade head``, and ``tests/unit/test_billing_migration_types.py`` compares
every column declared here against ``db_schema`` without needing a server.

Revision ID: b7e14c9d82a3
Revises: a3f5c2b81d47
Create Date: 2026-09-08 11:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b7e14c9d82a3"
# NOTE: single line on purpose. #36 adds a migration off the same head, so when the two
# branches are stacked one of them has to be re-pointed — and that must be a one-line
# change, not an archaeology exercise.
down_revision: str | None = "a3f5c2b81d47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mirrors ``leadquali.adapters.db_schema.STRIPE_EVENT_STATUSES`` and
#: ``leadquali.app.billing.EventStatus``. Restated as literals because a CHECK constraint
#: has to be one in the DDL, and because a migration has to keep working when the
#: application moves on. ``tests/unit/test_db_schema.py`` pins the three spellings together.
STRIPE_EVENT_STATUSES = ("pending", "processed", "failed")


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "stripe_events",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        # Nullable: see the module docstring. This is the invariant-4 exception.
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processed', 'failed')",
            name=op.f("ck_stripe_events_status_known"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_stripe_events_attempts_is_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stripe_events_tenant_id_tenants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_stripe_events")),
    )
    # The drain's only query, and nothing else reads this table in bulk. Partial so the
    # index is the size of the backlog rather than the size of history.
    op.create_index(
        "ix_stripe_events_pending",
        "stripe_events",
        ["received_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # "What has this tenant's billing done lately?" — the read that must filter on
    # tenant_id, which is why the nullable column is still indexed.
    op.create_index(
        "ix_stripe_events_tenant_id_received_at",
        "stripe_events",
        ["tenant_id", "received_at"],
        unique=False,
    )

    op.create_table(
        "usage_reports",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column(
            "reported_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_usage_reports_quantity_is_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_usage_reports_tenant_id_tenants"),
            # RESTRICT, not CASCADE: this is a record of a commercial fact, not a cache.
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "usage_date", name=op.f("pk_usage_reports")),
        sa.UniqueConstraint("external_id", name="uq_usage_reports_external_id"),
    )

    # The tenant link. All three are additive and none changes an existing row's behaviour:
    # every tenant on file comes out of this migration unlinked and undunned.
    op.add_column("tenants", sa.Column("stripe_customer_id", sa.Text(), nullable=True))
    op.add_column("tenants", sa.Column("stripe_subscription_id", sa.Text(), nullable=True))
    op.add_column(
        "tenants",
        sa.Column("dunning_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # Unique because two tenants sharing a Stripe customer would cross-bill, and that has
    # to be impossible rather than merely unlikely. NULLs are distinct in Postgres, so any
    # number of tenants may have no customer at all.
    op.create_unique_constraint("uq_tenants_stripe_customer_id", "tenants", ["stripe_customer_id"])
    op.create_unique_constraint(
        "uq_tenants_stripe_subscription_id", "tenants", ["stripe_subscription_id"]
    )


def downgrade() -> None:
    """Revert this revision.

    ``stripe_events`` and ``usage_reports`` are dropped outright, and unlike #33's rollup
    **neither is recomputable**. Dropping ``stripe_events`` loses the record of what Stripe
    told us; dropping ``usage_reports`` loses the record of what we told Stripe, which is
    the thing that stops a day being billed twice — so a downgrade followed by a re-upgrade
    and a re-run of the daily job would re-report every day inside Stripe's 24-hour
    deduplication window and bill everything older than that a second time.

    Export both tables before running this. It is written down here rather than in a
    runbook because this is where somebody will be standing when they need it.
    """
    op.drop_constraint("uq_tenants_stripe_subscription_id", "tenants", type_="unique")
    op.drop_constraint("uq_tenants_stripe_customer_id", "tenants", type_="unique")
    op.drop_column("tenants", "dunning_until")
    op.drop_column("tenants", "stripe_subscription_id")
    op.drop_column("tenants", "stripe_customer_id")
    op.drop_table("usage_reports")
    op.drop_index("ix_stripe_events_tenant_id_received_at", table_name="stripe_events")
    op.drop_index("ix_stripe_events_pending", table_name="stripe_events")
    op.drop_table("stripe_events")
