"""retention windows and the erasure audit log

Issue #37. Two per-tenant retention windows, one audit table, and one index, in a single
revision because they are one feature: a purge job with nowhere to record what it deleted
is half a deployment.

**``tenants.raw_retention_days`` / ``tenants.assessment_retention_days``** are the two
tiers. The first is how long ``leads.raw_payload`` — the personal data — is kept; the
second is how long the lead row and everything hanging off it is kept. Both are
``NOT NULL`` with a server default rather than nullable "unset means the default": a
retention window is a contractual term, it is negotiated per customer, and
``SELECT slug, raw_retention_days FROM tenants`` is the query an auditor actually runs.
Nullable columns would make the answer "90, unless it is NULL, in which case look in the
code".

Existing rows take the defaults, which is the right outcome and worth saying out loud: no
customer has agreed to anything else yet, and a migration is not the place to invent a
shorter window for somebody's live data.

The CHECKs are the interesting half. Zero days is not a policy but an outage — every lead
would be redacted by the next run of the purge, including the one being qualified right
now — so both windows are positive. And ``raw <= assessment`` because the tier split only
means anything in one direction: keeping the payload longer than the record it belongs to
would have the purge delete the lead, payload and all, while the payload's own window still
had months to run.

**``erasure_log``** is the evidence half of a deletion request. Two decisions in it:

* The subject is a **SHA-256**, never an address. A table whose entire purpose is recording
  that somebody's personal data was destroyed must not become the last place it is stored.
  A controller checking the row recomputes the hash from the address they already hold —
  which is also why the digest's shape is constrained, since a truncated or upper-cased
  value would silently fail to match ``leads.contact_email_hash``.
* The tenant foreign key is **RESTRICT**, unlike ``tenant_api_keys`` and
  ``tenant_config_versions``, which cascade. Those are the customer's own configuration.
  This is evidence about a *third party's* rights and has to survive the customer's account
  being closed, which is exactly the moment somebody asks whether the erasure happened.
  Nothing in the codebase deletes a tenant row; this constraint is what keeps that true
  when somebody tries.

**``ix_leads_tenant_id_contact_email_hash``** is what makes a deletion request answerable
in the time an SLA promises. Without it, finding a person's leads is a scan of everything
the tenant has ever received; with it, the whole point of storing the hash — being able to
answer "what do you hold about me?" without scanning JSONB — is true in practice and not
just in principle. It is a plain b-tree on ``(tenant_id, contact_email_hash)``: the column
is nullable and the index simply does not contain the NULLs.

Written by hand rather than autogenerated so the reasoning above sits with the DDL;
``tests/integration/test_migrations.py`` still asserts that autogenerate produces an empty
diff after ``upgrade head``.

Revision ID: c4a8f0e35b71
Revises: b6d2e94f7a13
Create Date: 2026-09-17 10:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c4a8f0e35b71"
down_revision: str | None = "b6d2e94f7a13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Tier 1. Mirrors ``leadquali.adapters.db_schema.DEFAULT_RAW_RETENTION_DAYS``, restated as
#: a literal because a migration has to keep working when the application moves on.
DEFAULT_RAW_RETENTION_DAYS = 90

#: Tier 2. Mirrors ``db_schema.DEFAULT_ASSESSMENT_RETENTION_DAYS``.
DEFAULT_ASSESSMENT_RETENTION_DAYS = 730


def upgrade() -> None:
    """Apply this revision."""
    op.add_column(
        "tenants",
        sa.Column(
            "raw_retention_days",
            sa.Integer(),
            server_default=sa.text(str(DEFAULT_RAW_RETENTION_DAYS)),
            nullable=False,
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "assessment_retention_days",
            sa.Integer(),
            server_default=sa.text(str(DEFAULT_ASSESSMENT_RETENTION_DAYS)),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_tenants_retention_windows_are_positive"),
        "tenants",
        "raw_retention_days > 0 AND assessment_retention_days > 0",
    )
    op.create_check_constraint(
        op.f("ck_tenants_raw_retention_within_assessment_retention"),
        "tenants",
        "raw_retention_days <= assessment_retention_days",
    )

    op.create_index(
        op.f("ix_leads_tenant_id_contact_email_hash"),
        "leads",
        ["tenant_id", "contact_email_hash"],
        unique=False,
    )

    op.create_table(
        "erasure_log",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("leads_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("assessments_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "routing_events_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("feedback_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "golden_promotions_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("matched_by_hash", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "matched_by_payload_scan", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("requested_by", sa.Text(), nullable=False),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "leads_deleted >= 0 AND assessments_deleted >= 0 AND routing_events_deleted >= 0 "
            "AND feedback_deleted >= 0 AND golden_promotions_deleted >= 0 "
            "AND matched_by_hash >= 0 AND matched_by_payload_scan >= 0",
            name=op.f("ck_erasure_log_counts_are_not_negative"),
        ),
        sa.CheckConstraint(
            "leads_deleted <= matched_by_hash + matched_by_payload_scan",
            name=op.f("ck_erasure_log_matches_account_for_the_leads_deleted"),
        ),
        sa.CheckConstraint(
            "requested_by <> ''", name=op.f("ck_erasure_log_requested_by_not_blank")
        ),
        sa.CheckConstraint(
            "subject_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_erasure_log_subject_hash_is_a_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_erasure_log_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_erasure_log")),
    )
    op.create_index(
        op.f("ix_erasure_log_subject_hash"), "erasure_log", ["subject_hash"], unique=False
    )
    op.create_index(
        op.f("ix_erasure_log_tenant_id_completed_at"),
        "erasure_log",
        ["tenant_id", "completed_at"],
        unique=False,
    )


def downgrade() -> None:
    """Revert this revision.

    ``erasure_log`` is the one that hurts, and it hurts more than #36's config history did:
    it is the only record that a person's data was destroyed on request, nothing can
    recompute it, and it is the artifact produced *for* somebody outside this company. If
    this revision has ever been live with real traffic on it, export the table before
    downgrading past it.

    Dropping the two ``tenants`` columns loses any window a customer negotiated away from
    the default, which then silently reverts to 90/730 on the way back up.
    """
    op.drop_index(op.f("ix_erasure_log_tenant_id_completed_at"), table_name="erasure_log")
    op.drop_index(op.f("ix_erasure_log_subject_hash"), table_name="erasure_log")
    op.drop_table("erasure_log")
    op.drop_index(op.f("ix_leads_tenant_id_contact_email_hash"), table_name="leads")
    op.drop_constraint(
        op.f("ck_tenants_raw_retention_within_assessment_retention"), "tenants", type_="check"
    )
    op.drop_constraint(op.f("ck_tenants_retention_windows_are_positive"), "tenants", type_="check")
    op.drop_column("tenants", "assessment_retention_days")
    op.drop_column("tenants", "raw_retention_days")
