"""initial schema

Creates the five tables of plan section 4 in one revision: ``tenants``, ``leads``,
``assessments``, ``routing_events`` and ``feedback``.

Generated by ``alembic revision --autogenerate`` against
``leadquali.adapters.db_schema.metadata`` and left byte-for-byte equivalent to it on
purpose: re-running autogenerate after ``upgrade head`` must produce an empty diff, and
``tests/integration/test_migrations.py`` asserts exactly that. Hand-editing the DDL here
without the matching model change is how a schema and its application quietly diverge.

Two things this revision establishes that are expensive to add later:

* ``tenant_id NOT NULL REFERENCES tenants(id)`` on every child table — including
  ``routing_events`` and ``feedback``, where it is also reachable through ``lead_id``.
  Plan section 4's sketch omits it there; carrying it anyway is what lets every repository
  method filter by tenant without a join, and retrofitting multi-tenancy is a rewrite.
* ``UNIQUE (tenant_id, submission_id)`` on ``leads`` — the idempotency key. SQS delivers at
  least once, so the worker will see the same submission twice; without this constraint the
  second delivery inserts a second lead and sales is emailed twice.

Every foreign key is ``ON DELETE CASCADE``, so deleting a tenant removes everything it
owns — the shape a GDPR erasure request needs.

Revision ID: 484c0bafc202
Revises:
Create Date: 2026-09-02 04:09:52.244108
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "484c0bafc202"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "icp_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("api_key_hash", sa.Text(), nullable=True),
        sa.Column("hmac_secret_ref", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'disabled')", name=op.f("ck_tenants_status_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'received'"), nullable=False
        ),
        sa.Column("contact_email_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("submission_id <> ''", name=op.f("ck_leads_submission_id_not_blank")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_leads_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("tenant_id", "submission_id", name="uq_leads_tenant_id_submission_id"),
    )
    op.create_index(
        "ix_leads_tenant_id_received_at", "leads", ["tenant_id", "received_at"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("dimension_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "missing_information",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("effort", sa.String(length=16), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cache_creation_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "tier IN ('hot', 'warm', 'cold', 'disqualified')",
            name=op.f("ck_assessments_tier_known"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_assessments_confidence_is_a_probability"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 "
            "AND cache_creation_tokens >= 0 AND cost_usd >= 0 AND latency_ms >= 0",
            name=op.f("ck_assessments_usage_is_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_assessments_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_assessments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index("ix_assessments_lead_id", "assessments", ["lead_id"], unique=False)
    op.create_index(
        "ix_assessments_tenant_id_tier_created_at",
        "assessments",
        ["tenant_id", "tier", "created_at"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("rater", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('good', 'bad', 'unsure')", name=op.f("ck_feedback_verdict_known")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_feedback_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_feedback_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_index("ix_feedback_lead_id", "feedback", ["lead_id"], unique=False)
    op.create_index(
        "ix_feedback_tenant_id_verdict_created_at",
        "feedback",
        ["tenant_id", "verdict", "created_at"],
        unique=False,
    )
    op.create_table(
        "routing_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("destination", sa.Text(), nullable=True),
        sa.Column("dispatched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_routing_events_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_routing_events_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_events")),
    )
    op.create_index("ix_routing_events_lead_id", "routing_events", ["lead_id"], unique=False)
    op.create_index(
        "ix_routing_events_tenant_id_created_at",
        "routing_events",
        ["tenant_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_index("ix_routing_events_tenant_id_created_at", table_name="routing_events")
    op.drop_index("ix_routing_events_lead_id", table_name="routing_events")
    op.drop_table("routing_events")
    op.drop_index("ix_feedback_tenant_id_verdict_created_at", table_name="feedback")
    op.drop_index("ix_feedback_lead_id", table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("ix_assessments_tenant_id_tier_created_at", table_name="assessments")
    op.drop_index("ix_assessments_lead_id", table_name="assessments")
    op.drop_table("assessments")
    op.drop_index("ix_leads_tenant_id_received_at", table_name="leads")
    op.drop_table("leads")
    op.drop_table("tenants")
