"""The wire contract for ``POST /leads``. Attacker-controlled, and typed accordingly.

This is the ingest API's own schema, deliberately separate from
:class:`~leadquali.prompts.lead.LeadSubmission`. They answer different questions —
"what may a stranger send us?" and "what does the renderer need?" — and they change for
different reasons: adding a form field is a change here, changing how a lead is presented
to the model is a change there. :meth:`LeadForm.to_submission` is the one seam between
them, and it is a mapping rather than an inheritance so neither can quietly acquire the
other's fields.

Everything is bounded. The envelope forbids unknown keys, every string has a maximum
length, and unknown *form* fields are kept but only as scalars: a form nobody anticipated
carries the buying signal often enough to be worth keeping, and a nested JSON document
nobody anticipated is a way to make the server do work. The caps here are generous
compared to the renderer's (#12 truncates rather than rejects), because a long genuine
enquiry must not be answered with a 422 — the real bound on request size is the body-size
limit applied before any of this runs.
"""

from __future__ import annotations

from datetime import datetime
from typing import Final, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from leadquali.prompts.lead import LeadSubmission

#: Largest body the endpoint will read, before parsing. A web-form lead is a few hundred
#: bytes; 64 KiB is room for a very long enquiry and far less than it takes to make
#: parsing expensive. Enforced on the stream, so an oversized post is refused without ever
#: being held in memory in full.
MAX_BODY_BYTES: Final[int] = 64 * 1024

#: The idempotency key's shape. Generated by the form (a UUID4 is the obvious choice), so
#: it is long enough to be unguessable and constrained enough to be safe in a log line.
SUBMISSION_ID_PATTERN: Final[str] = r"^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$"

#: Where the lead came from, recorded on the row. A short identifier, not free text.
SOURCE_PATTERN: Final[str] = r"^[a-z][a-z0-9_-]{0,31}$"

MAX_SHORT_FIELD_CHARS: Final[int] = 1_000
MAX_MESSAGE_CHARS: Final[int] = 20_000
MAX_EXTRA_FIELDS: Final[int] = 50

#: A day. Anything outside this is not a plausible form-fill duration, in either
#: direction, and a negative value is a bot signal the pre-filters read (not an error).
_MAX_ELAPSED_MS: Final[int] = 24 * 60 * 60 * 1_000


class LeadForm(BaseModel):
    """The form's fields. Known ones are typed; anything else is kept as a scalar."""

    model_config = ConfigDict(extra="allow")

    full_name: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    email: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    company: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    role: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    phone: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    website: str | None = Field(default=None, max_length=MAX_SHORT_FIELD_CHARS)
    message: str | None = Field(default=None, max_length=MAX_MESSAGE_CHARS)

    @model_validator(mode="after")
    def _unknown_fields_are_scalars(self) -> LeadForm:
        """An unanticipated field is welcome; an unanticipated document is not.

        A nested object or array in a form field is not something a form produces, and
        accepting one would mean stringifying arbitrarily deep structure on the request
        path. Rejecting it keeps the work per request bounded by the body-size limit.
        """
        for name, value in (self.model_extra or {}).items():
            if isinstance(value, dict | list):
                raise ValueError(f"form field '{name[:64]}' must be a single value, not a list")
        return self

    def to_submission(self) -> LeadSubmission:
        """Map the wire form onto the renderer's input.

        Unknown fields become :attr:`~leadquali.prompts.lead.LeadSubmission.extra`,
        stringified and capped in count. The renderer sanitises, truncates and escapes
        every one of them, so nothing here needs to decide whether a value is safe — only
        whether it is bounded.
        """
        extras: dict[str, str | None] = {}
        for name, value in list((self.model_extra or {}).items())[:MAX_EXTRA_FIELDS]:
            extras[name] = None if value is None else str(value)
        return LeadSubmission(
            full_name=self.full_name,
            email=self.email,
            company=self.company,
            role=self.role,
            phone=self.phone,
            website=self.website,
            message=self.message,
            extra=extras,
        )


class LeadIngestRequest(BaseModel):
    """One signed form post.

    ``extra="forbid"`` at this level and ``extra="allow"`` inside :attr:`form` is the
    deliberate asymmetry: the envelope is our protocol and a key we do not recognise in it
    means the client and the server disagree about the protocol, which is worth a 422. The
    form is the customer's, and a field we do not recognise there is just a field.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    submission_id: str = Field(
        pattern=SUBMISSION_ID_PATTERN,
        description="Client-generated idempotency key, unique per tenant. A UUID4 is ideal.",
    )
    form: LeadForm = Field(description="The form's fields, known and unknown.")
    source: str = Field(
        default="web_form",
        pattern=SOURCE_PATTERN,
        description="Which of the tenant's inbound channels this arrived on.",
    )
    honeypot: str | None = Field(
        default=None,
        max_length=MAX_SHORT_FIELD_CHARS,
        description=(
            "Value of the form's hidden decoy field. Send it always, empty or absent when "
            "the visitor left it alone; anything non-blank suppresses the submission."
        ),
    )
    elapsed_ms: int | None = Field(
        default=None,
        ge=-_MAX_ELAPSED_MS,
        le=_MAX_ELAPSED_MS,
        description=(
            "Milliseconds between rendering the form and posting it. Omit if the form does "
            "not measure it; an implausibly small value suppresses the submission."
        ),
    )


class IngestAccepted(BaseModel):
    """The 202 body. Identical for an accepted, suppressed or duplicate submission.

    Saying no more than this is deliberate. A bot that learns *which* filter caught it can
    tune around it in minutes, so the endpoint answers every well-formed, correctly signed
    post the same way and records the difference where only the tenant can see it.
    """

    model_config = ConfigDict(frozen=True)

    submission_id: str = Field(description="Echoed back, so the client can correlate a retry.")
    status: Literal["accepted"] = Field(
        default="accepted", description="Always 'accepted'. The verdict is not public."
    )
    received_at: datetime = Field(description="When the lead was recorded, UTC.")


class ErrorResponse(BaseModel):
    """Every non-2xx body. One sentence, and never a hint about what exists."""

    model_config = ConfigDict(frozen=True)

    detail: str


class FieldError(BaseModel):
    """One schema violation, in the terms the client can act on."""

    model_config = ConfigDict(frozen=True)

    field: str
    message: str


class ValidationErrorResponse(ErrorResponse):
    """A 422 body: what was wrong, without echoing back what was sent."""

    errors: list[FieldError] = Field(default_factory=list)


__all__ = [
    "MAX_BODY_BYTES",
    "MAX_EXTRA_FIELDS",
    "MAX_MESSAGE_CHARS",
    "MAX_SHORT_FIELD_CHARS",
    "SOURCE_PATTERN",
    "SUBMISSION_ID_PATTERN",
    "ErrorResponse",
    "FieldError",
    "IngestAccepted",
    "LeadForm",
    "LeadIngestRequest",
    "ValidationErrorResponse",
]
